### ISSUE TITLE
One single api endpoint to update proposer data

### ISSUE THREAD

**Issue by g11tech** [ethereum/keymanager-APIs#49]
Right now, there seem to be different endpoints to fetch/update/delete fee recipient, I propose there be just a single endpoint to update the proposer information of a validator pubkey, we should also include graffiti and builder info as part of proposer data update

```
  graffiti: 'default graffiti'
  strict_fee_recipient_check: true
  fee_recipient: '0xcccccccccccccccccccccccccccccccccccccccc'
  builder:
    enabled: true
    gas_limit: "30000000"
```
cc @james-prysm 
If you feel this is a good way to go, I can do a PR to update the api section
